/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFallbackManager,
  IFallbackManagerInterface,
} from "../../../contracts/interfaces/IFallbackManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "handler",
        type: "address",
      },
    ],
    name: "ChangedFallbackHandler",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "handler",
        type: "address",
      },
    ],
    name: "setFallbackHandler",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFallbackManager__factory {
  static readonly abi = _abi;
  static createInterface(): IFallbackManagerInterface {
    return new utils.Interface(_abi) as IFallbackManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFallbackManager {
    return new Contract(address, _abi, signerOrProvider) as IFallbackManager;
  }
}
