/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governor from "./governor";
export type { governor };
import type * as token from "./token";
export type { token };
import type * as treasury from "./treasury";
export type { treasury };
