export const analyticsEvents = {
  DaoCreatePageOpened: 'DaoCreatePageOpened',
  DaoCreateFormSubmitted: 'DaoCreateFormSubmitted',
  DaoDashboardPageOpened: 'DaoDashboardPageOpened',
  ModifyGovernancePageOpened: 'ModifyGovernancePageOpened',
  HierarchyPageOpened: 'HierarchyPageOpened',
  RolesPageOpened: 'RolesPageOpened',
  RolesEditPageOpened: 'RolesEditPageOpened',
  SubDaoCreatePageOpened: 'SubDaoCreatePageOpened',
  ProposalTemplatesPageOpened: 'ProposalTemplatesPageOpened',
  CreateProposalTemplatePageOpened: 'CreateProposalTemplatePageOpened',
  ProposalsPageOpened: 'ProposalsPageOpened',
  ProposalDetailsPageOpened: 'ProposalDetailsPageOpened',
  CreateProposalPageOpened: 'CreateProposalPageOpened',
  SafeProposalWithActionsCreatePageOpened: 'SafeProposalWithActionsCreatePageOpened',
  SafeSettingsPageOpened: 'SafeSettingsPageOpened',
  TreasuryPageOpened: 'TreasuryPageOpened',
  SablierProposalCreatePageOpened: 'SablierProposalCreatePageOpened',
};
