/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TokenFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createToken(string,string,address[],uint256[],uint256,address)": FunctionFragment;
    "wrapToken(address,string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createToken",
    values: [string, string, string[], BigNumberish[], BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapToken",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wrapToken", data: BytesLike): Result;

  events: {
    "TokenDeployed(address,string,string)": EventFragment;
    "TokenWrapped(address,address,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TokenDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenWrapped"): EventFragment;
}

export type TokenDeployedEvent = TypedEvent<
  [string, string, string] & {
    tokenAddress: string;
    name: string;
    symbol: string;
  }
>;

export type TokenWrappedEvent = TypedEvent<
  [string, string, string, string] & {
    underlyingToken: string;
    wrappedAddress: string;
    name: string;
    symbol: string;
  }
>;

export class TokenFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TokenFactoryInterface;

  functions: {
    createToken(
      tokenName: string,
      symbol: string,
      hodlers: string[],
      allocations: BigNumberish[],
      totalSupply: BigNumberish,
      treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    wrapToken(
      tokenAddress: string,
      votingTokenName: string,
      votingTokenSymbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createToken(
    tokenName: string,
    symbol: string,
    hodlers: string[],
    allocations: BigNumberish[],
    totalSupply: BigNumberish,
    treasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  wrapToken(
    tokenAddress: string,
    votingTokenName: string,
    votingTokenSymbol: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createToken(
      tokenName: string,
      symbol: string,
      hodlers: string[],
      allocations: BigNumberish[],
      totalSupply: BigNumberish,
      treasury: string,
      overrides?: CallOverrides
    ): Promise<string>;

    wrapToken(
      tokenAddress: string,
      votingTokenName: string,
      votingTokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "TokenDeployed(address,string,string)"(
      tokenAddress?: null,
      name?: null,
      symbol?: null
    ): TypedEventFilter<
      [string, string, string],
      { tokenAddress: string; name: string; symbol: string }
    >;

    TokenDeployed(
      tokenAddress?: null,
      name?: null,
      symbol?: null
    ): TypedEventFilter<
      [string, string, string],
      { tokenAddress: string; name: string; symbol: string }
    >;

    "TokenWrapped(address,address,string,string)"(
      underlyingToken?: null,
      wrappedAddress?: null,
      name?: null,
      symbol?: null
    ): TypedEventFilter<
      [string, string, string, string],
      {
        underlyingToken: string;
        wrappedAddress: string;
        name: string;
        symbol: string;
      }
    >;

    TokenWrapped(
      underlyingToken?: null,
      wrappedAddress?: null,
      name?: null,
      symbol?: null
    ): TypedEventFilter<
      [string, string, string, string],
      {
        underlyingToken: string;
        wrappedAddress: string;
        name: string;
        symbol: string;
      }
    >;
  };

  estimateGas: {
    createToken(
      tokenName: string,
      symbol: string,
      hodlers: string[],
      allocations: BigNumberish[],
      totalSupply: BigNumberish,
      treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    wrapToken(
      tokenAddress: string,
      votingTokenName: string,
      votingTokenSymbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createToken(
      tokenName: string,
      symbol: string,
      hodlers: string[],
      allocations: BigNumberish[],
      totalSupply: BigNumberish,
      treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    wrapToken(
      tokenAddress: string,
      votingTokenName: string,
      votingTokenSymbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
