/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IClaimSubsidiaryInterface extends utils.Interface {
  functions: {
    "calculateClaimAmount(address)": FunctionFragment;
    "claimSnap(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "calculateClaimAmount" | "claimSnap"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateClaimAmount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimSnap",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateClaimAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimSnap", data: BytesLike): Result;

  events: {
    "SnapAdded(address,address,uint256)": EventFragment;
    "SnapClaimed(address,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SnapAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SnapClaimed"): EventFragment;
}

export interface SnapAddedEventObject {
  pToken: string;
  cToken: string;
  pAllocation: BigNumber;
}
export type SnapAddedEvent = TypedEvent<
  [string, string, BigNumber],
  SnapAddedEventObject
>;

export type SnapAddedEventFilter = TypedEventFilter<SnapAddedEvent>;

export interface SnapClaimedEventObject {
  pToken: string;
  cToken: string;
  claimer: string;
  amount: BigNumber;
}
export type SnapClaimedEvent = TypedEvent<
  [string, string, string, BigNumber],
  SnapClaimedEventObject
>;

export type SnapClaimedEventFilter = TypedEventFilter<SnapClaimedEvent>;

export interface IClaimSubsidiary extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IClaimSubsidiaryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    calculateClaimAmount(
      claimer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { cTokenAllocation: BigNumber }>;

    claimSnap(
      claimer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  calculateClaimAmount(
    claimer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimSnap(
    claimer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    calculateClaimAmount(
      claimer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimSnap(
      claimer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SnapAdded(address,address,uint256)"(
      pToken?: null,
      cToken?: null,
      pAllocation?: null
    ): SnapAddedEventFilter;
    SnapAdded(
      pToken?: null,
      cToken?: null,
      pAllocation?: null
    ): SnapAddedEventFilter;

    "SnapClaimed(address,address,address,uint256)"(
      pToken?: PromiseOrValue<string> | null,
      cToken?: PromiseOrValue<string> | null,
      claimer?: PromiseOrValue<string> | null,
      amount?: null
    ): SnapClaimedEventFilter;
    SnapClaimed(
      pToken?: PromiseOrValue<string> | null,
      cToken?: PromiseOrValue<string> | null,
      claimer?: PromiseOrValue<string> | null,
      amount?: null
    ): SnapClaimedEventFilter;
  };

  estimateGas: {
    calculateClaimAmount(
      claimer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimSnap(
      claimer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculateClaimAmount(
      claimer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimSnap(
      claimer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
