/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governor from "./governor";
export * as token from "./token";
export * as treasury from "./treasury";
