/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as safeProxySol from "./SafeProxy.sol";
export { IProxyCreationCallback__factory } from "./IProxyCreationCallback__factory";
export { SafeProxyFactory__factory } from "./SafeProxyFactory__factory";
